# https://taskfile.dev

version: '3'

tasks:
  install:
    cmd: yarn

  run:
    cmd: yarn dev

  build:
    cmd: yarn build

  lint:
    cmd: yarn lint

  format:
    cmd: yarn format

  test:
    cmd: yarn test

  generate-api-client:
    cmd: yarn generate-api-client
