#!/bin/bash
echo -e "\e[1;34mFormatting client code...\e[0m"
cd client && yarn prettier $(git -C .. diff --cached --name-only --diff-filter=ACMR | grep "^client/" | sed 's|^client/||' | sed 's| |\\ |g') --write --ignore-unknown

echo -e "\n\e[1;34mFormatting api code...\e[0m"
cd ../api && uvx ruff format $(git -C .. diff --cached --name-only --diff-filter=ACMR | grep "^api/" | grep "\.py$" | sed 's|^api/||' | sed 's| |\\ |g')

git update-index --again