exclude: ^(scripts/.*)(\.github/.*)(\.devcontainer/.*)

repos:
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v4.1.0 # MUST match your pre-commit version
    hooks:
      - id: sub-pre-commit
        alias: client
        name: "pre-commit for client/"
        args: ["-p", "client"]
        files: "^client/.*"
        stages: ["pre-commit"]
        fail_fast: false
      - id: sub-pre-commit
        alias: api
        name: "pre-commit for api/"
        args: ["-p", "api"]
        files: "^api/.*"
        stages: ["pre-commit"]
        fail_fast: false
