name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'develop'

jobs:
  docker_publish_dev_branch:
    name: Build and Push Development Branch Docker Image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          
      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ilhanyapici.com
          username: schoolmarks
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.ilhanyapici.com/schoolmarks/api:${{ github.event.inputs.branch }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=registry.ilhanyapici.com/schoolmarks/api:develop
          cache-to: type=inline
          provenance: false