# https://taskfile.dev

version: "3"

vars:
  DJANGO_SETTINGS_MODULE: schoolmarksapi.settings.dev

tasks:
  install:
    cmd: uv sync

  run:
    cmd: uv run manage.py runserver --settings={{.DJANGO_SETTINGS_MODULE}}

  run-celery:
    cmd: DJANGO_SETTINGS_MODULE={{.DJANGO_SETTINGS_MODULE}} uv run celery -A common worker -l info

  generate-schema:
    cmd: uv run manage.py spectacular --file openapi-schema.yml

  lint:
    cmd: uvx ruff check

  format:
    cmd: uvx ruff format

  make-migrations:
    cmd: uv run manage.py makemigrations schoolmarksapi

  migrate:
    cmd: uv run manage.py migrate
